import * as THREE from "three";
import { OrbitControls } from "https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/controls/OrbitControls.js";
import { TransformControls } from "https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/controls/TransformControls.js";
import { GLTFLoader } from "https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/loaders/GLTFLoader.js";

const canvas = document.querySelector("#scene"), list = document.querySelector("#object-list"), selection = document.querySelector("#selection"), transformSection = document.querySelector("#transform"), materialSection = document.querySelector("#material");
const renderer = new THREE.WebGLRenderer({ canvas, antialias: true }); renderer.setPixelRatio(Math.min(devicePixelRatio, 2));
const scene = new THREE.Scene(); scene.background = new THREE.Color(0x79b9e2); scene.add(new THREE.HemisphereLight(0xffffff, 0x253d29, 2.5)); const light = new THREE.DirectionalLight(0xffffff, 2); light.position.set(4, 8, 5); scene.add(light); scene.add(new THREE.GridHelper(30, 30, 0x4f8498, 0x416c51));
const camera = new THREE.PerspectiveCamera(55, 1, .01, 1000); camera.position.set(4, 3.5, 6); const orbit = new OrbitControls(camera, canvas); orbit.mouseButtons.LEFT = -1; orbit.mouseButtons.MIDDLE = THREE.MOUSE.PAN; orbit.mouseButtons.RIGHT = THREE.MOUSE.ROTATE; orbit.target.set(0, 1, 0); orbit.update();
const transform = new TransformControls(camera, canvas); transform.addEventListener("dragging-changed", (event) => orbit.enabled = !event.value); transform.addEventListener("objectChange", syncInspector); scene.add(transform.getHelper());
const content = new THREE.Group(); content.name = "Scene content"; scene.add(content); const raycaster = new THREE.Raycaster(), pointer = new THREE.Vector2(), selectedSet = new Set(); const selectionBox = document.querySelector("#selection-box"); let selected = null, selectionStart = null;
function resize(){renderer.setSize(canvas.clientWidth, canvas.clientHeight, false); camera.aspect=canvas.clientWidth/canvas.clientHeight; camera.updateProjectionMatrix()} addEventListener("resize",resize); resize();
function meshes(root){const result=[];root.traverse((node)=>{if(node.isMesh)result.push(node)});return result}
function select(object, append = false){if(!append)selectedSet.clear();selectedSet.add(object);selected=object; transform.attach(object); selection.textContent=selectedSet.size>1?`${selectedSet.size} objects selected`:object.name||"Mesh"; transformSection.hidden=false; const hasMaterial=Boolean(object.material); materialSection.hidden=!hasMaterial; rebuildList(); syncInspector()}
function rebuildList(){list.innerHTML="";meshes(content).forEach((object,index)=>{if(!object.name)object.name=`Mesh ${index+1}`;const button=document.createElement("button");button.className=`object${selectedSet.has(object)?" selected":""}`;button.textContent=object.name;button.onclick=()=>select(object);list.append(button)})}
function syncInspector(){if(!selected)return;document.querySelectorAll("[data-transform]").forEach((input)=>{const [group,axis]=input.dataset.transform.split(".");let value=selected[group][axis];if(group==="rotation")value=THREE.MathUtils.radToDeg(value);input.value=Number(value).toFixed(3)});const material=selected.material;if(material){document.querySelector("#material-color").value=`#${material.color.getHexString()}`;document.querySelector("#material-metalness").value=material.metalness??0;document.querySelector("#material-roughness").value=material.roughness??.5}}
document.querySelectorAll("[data-transform]").forEach((input)=>input.addEventListener("change",()=>{if(!selected)return;const [group,axis]=input.dataset.transform.split(".");let value=Number(input.value);if(group==="rotation")value=THREE.MathUtils.degToRad(value);selected[group][axis]=value;syncInspector()}));
for(const id of ["material-color","material-metalness","material-roughness"]){document.querySelector(`#${id}`).addEventListener("input",(event)=>{if(!selected?.material)return;const m=selected.material;if(id==="material-color")m.color.set(event.target.value);else m[id.replace("material-","")]=Number(event.target.value);m.needsUpdate=true})}
function selectInRectangle(left, top, right, bottom){selectedSet.clear();meshes(content).forEach((object)=>{const point=object.getWorldPosition(new THREE.Vector3()).project(camera);const x=(point.x+1)/2*canvas.clientWidth,y=(-point.y+1)/2*canvas.clientHeight;if(x>=left&&x<=right&&y>=top&&y<=bottom)selectedSet.add(object)});selected=[...selectedSet].at(-1)??null;if(selected){transform.attach(selected);selection.textContent=selectedSet.size>1?`${selectedSet.size} objects selected`:selected.name||"Mesh";transformSection.hidden=false;materialSection.hidden=!selected.material;syncInspector()}else{transform.detach();selection.textContent="Select an object";transformSection.hidden=true;materialSection.hidden=true}rebuildList()}
canvas.addEventListener("contextmenu",(event)=>event.preventDefault());
canvas.addEventListener("pointerdown",(event)=>{if(event.button!==0||transform.dragging||transform.axis)return;const rect=canvas.getBoundingClientRect();selectionStart={x:event.clientX-rect.left,y:event.clientY-rect.top};selectionBox.style.display="block";selectionBox.style.left=`${selectionStart.x}px`;selectionBox.style.top=`${selectionStart.y}px`;selectionBox.style.width="0px";selectionBox.style.height="0px";canvas.setPointerCapture(event.pointerId)});
canvas.addEventListener("pointermove",(event)=>{if(!selectionStart)return;const rect=canvas.getBoundingClientRect(),x=event.clientX-rect.left,y=event.clientY-rect.top;selectionBox.style.left=`${Math.min(selectionStart.x,x)}px`;selectionBox.style.top=`${Math.min(selectionStart.y,y)}px`;selectionBox.style.width=`${Math.abs(x-selectionStart.x)}px`;selectionBox.style.height=`${Math.abs(y-selectionStart.y)}px`});
canvas.addEventListener("pointerup",(event)=>{if(!selectionStart)return;const rect=canvas.getBoundingClientRect(),x=event.clientX-rect.left,y=event.clientY-rect.top;const left=Math.min(selectionStart.x,x),right=Math.max(selectionStart.x,x),top=Math.min(selectionStart.y,y),bottom=Math.max(selectionStart.y,y);selectionBox.style.display="none";selectionStart=null;if(right-left<5&&bottom-top<5){pointer.x=x/rect.width*2-1;pointer.y=-(y/rect.height)*2+1;raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(content.children,true)[0];if(hit)select(hit.object);else selectInRectangle(left,top,right,bottom)}else selectInRectangle(left,top,right,bottom)});
function setTool(mode){transform.setMode(mode);document.querySelectorAll("[data-tool]").forEach((button)=>button.classList.toggle("active",button.dataset.tool===mode))} addEventListener("keydown",(event)=>{if(event.key.toLowerCase()==="w")setTool("translate");if(event.key.toLowerCase()==="e")setTool("rotate");if(event.key.toLowerCase()==="r")setTool("scale")});
document.querySelector("#move-tool").dataset.tool="translate";document.querySelector("#rotate-tool").dataset.tool="rotate";document.querySelector("#scale-tool").dataset.tool="scale";document.querySelector("#move-tool").onclick=()=>setTool("translate");document.querySelector("#rotate-tool").onclick=()=>setTool("rotate");document.querySelector("#scale-tool").onclick=()=>setTool("scale");setTool("translate");
document.querySelector("#add-cube").onclick=()=>{const cube=new THREE.Mesh(new THREE.BoxGeometry(1,1,1),new THREE.MeshStandardMaterial({color:0x4a9ee0,metalness:.2,roughness:.55}));cube.name="Cube";cube.position.y=.5;content.add(cube);select(cube)};
document.querySelector("#file-input").addEventListener("change",async(event)=>{for(const file of event.target.files){const url=URL.createObjectURL(file);new GLTFLoader().load(url,(gltf)=>{const model=gltf.scene;model.name=file.name.replace(/\.(glb|gltf)$/i,"");content.add(model);const box=new THREE.Box3().setFromObject(model);const center=box.getCenter(new THREE.Vector3());model.position.sub(center);select(meshes(model)[0]||model);URL.revokeObjectURL(url)},undefined,(error)=>console.error("Model import failed",error))}});
document.querySelector("#save-scene").onclick=()=>{const data=JSON.stringify(content.toJSON());const link=document.createElement("a");link.href=URL.createObjectURL(new Blob([data],{type:"application/json"}));link.download="xrflightsim-scene.json";link.click();URL.revokeObjectURL(link.href)};
renderer.setAnimationLoop(()=>{renderer.render(scene,camera)});
