import * as THREE from "three";
import { OrbitControls } from "https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/controls/OrbitControls.js";
import { TransformControls } from "https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/controls/TransformControls.js";
import { GLTFLoader } from "https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/loaders/GLTFLoader.js";

const canvas = document.querySelector("#scene"), list = document.querySelector("#object-list"), selection = document.querySelector("#selection"), transformSection = document.querySelector("#transform"), materialSection = document.querySelector("#material");
const renderer = new THREE.WebGLRenderer({ canvas, antialias: true }); renderer.setPixelRatio(Math.min(devicePixelRatio, 2));
const scene = new THREE.Scene(); scene.background = new THREE.Color(0x79b9e2); scene.add(new THREE.HemisphereLight(0xffffff, 0x253d29, 2.5)); const light = new THREE.DirectionalLight(0xffffff, 2); light.position.set(4, 8, 5); scene.add(light); scene.add(new THREE.GridHelper(30, 30, 0x4f8498, 0x416c51));
const camera = new THREE.PerspectiveCamera(55, 1, .01, 1000); camera.position.set(4, 3.5, 6); const orbit = new OrbitControls(camera, canvas); orbit.target.set(0, 1, 0); orbit.update();
const transform = new TransformControls(camera, canvas); transform.addEventListener("dragging-changed", (event) => orbit.enabled = !event.value); transform.addEventListener("objectChange", syncInspector); scene.add(transform);
const content = new THREE.Group(); content.name = "Scene content"; scene.add(content); const raycaster = new THREE.Raycaster(), pointer = new THREE.Vector2(); let selected = null;
function resize(){renderer.setSize(canvas.clientWidth, canvas.clientHeight, false); camera.aspect=canvas.clientWidth/canvas.clientHeight; camera.updateProjectionMatrix()} addEventListener("resize",resize); resize();
function meshes(root){const result=[];root.traverse((node)=>{if(node.isMesh)result.push(node)});return result}
function select(object){selected=object; transform.attach(object); selection.textContent=object.name||"Mesh"; transformSection.hidden=false; const hasMaterial=Boolean(object.material); materialSection.hidden=!hasMaterial; rebuildList(); syncInspector()}
function rebuildList(){list.innerHTML="";meshes(content).forEach((object,index)=>{if(!object.name)object.name=`Mesh ${index+1}`;const button=document.createElement("button");button.className=`object${object===selected?" selected":""}`;button.textContent=object.name;button.onclick=()=>select(object);list.append(button)})}
function syncInspector(){if(!selected)return;document.querySelectorAll("[data-transform]").forEach((input)=>{const [group,axis]=input.dataset.transform.split(".");let value=selected[group][axis];if(group==="rotation")value=THREE.MathUtils.radToDeg(value);input.value=Number(value).toFixed(3)});const material=selected.material;if(material){document.querySelector("#material-color").value=`#${material.color.getHexString()}`;document.querySelector("#material-metalness").value=material.metalness??0;document.querySelector("#material-roughness").value=material.roughness??.5}}
document.querySelectorAll("[data-transform]").forEach((input)=>input.addEventListener("change",()=>{if(!selected)return;const [group,axis]=input.dataset.transform.split(".");let value=Number(input.value);if(group==="rotation")value=THREE.MathUtils.degToRad(value);selected[group][axis]=value;syncInspector()}));
for(const id of ["material-color","material-metalness","material-roughness"]){document.querySelector(`#${id}`).addEventListener("input",(event)=>{if(!selected?.material)return;const m=selected.material;if(id==="material-color")m.color.set(event.target.value);else m[id.replace("material-","")]=Number(event.target.value);m.needsUpdate=true})}
canvas.addEventListener("pointerdown",(event)=>{if(event.button!==0||transform.dragging)return;const rect=canvas.getBoundingClientRect();pointer.x=(event.clientX-rect.left)/rect.width*2-1;pointer.y=-(event.clientY-rect.top)/rect.height*2+1;raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(content.children,true)[0];if(hit)select(hit.object)});
addEventListener("keydown",(event)=>{if(event.key.toLowerCase()==="w")transform.setMode("translate");if(event.key.toLowerCase()==="e")transform.setMode("rotate");if(event.key.toLowerCase()==="r")transform.setMode("scale")});
document.querySelector("#add-cube").onclick=()=>{const cube=new THREE.Mesh(new THREE.BoxGeometry(1,1,1),new THREE.MeshStandardMaterial({color:0x4a9ee0,metalness:.2,roughness:.55}));cube.name="Cube";cube.position.y=.5;content.add(cube);select(cube)};
document.querySelector("#file-input").addEventListener("change",async(event)=>{for(const file of event.target.files){const url=URL.createObjectURL(file);new GLTFLoader().load(url,(gltf)=>{const model=gltf.scene;model.name=file.name.replace(/\.(glb|gltf)$/i,"");content.add(model);const box=new THREE.Box3().setFromObject(model);const center=box.getCenter(new THREE.Vector3());model.position.sub(center);select(meshes(model)[0]||model);URL.revokeObjectURL(url)},undefined,(error)=>console.error("Model import failed",error))}});
document.querySelector("#save-scene").onclick=()=>{const data=JSON.stringify(content.toJSON());const link=document.createElement("a");link.href=URL.createObjectURL(new Blob([data],{type:"application/json"}));link.download="xrflightsim-scene.json";link.click();URL.revokeObjectURL(link.href)};
renderer.setAnimationLoop(()=>{renderer.render(scene,camera)});
